#! /bin/bash

read -p "Enter username to be deleted: " username

if [ "$username" = "root" ];
then
	echo "NO!"
	exit 1
fi

if ! id -u $username > /dev/null 2>&1;
then
	echo "User does not exist."
	exit 1
fi

if who | grep -wq $username;
then
	echo "Error: User is currently logged in. Please log out before deleting."
	exit 1
fi

sudo userdel -r $username
